### ISSUE TITLE
Stream subchannels are not deleted from the child list on client disconnect

### ISSUE THREAD

**Issue by fdenis1983** [shramov/tll#13]
While testing the test_stream_aggregate testcase, an assertion failure occurs after appending the following code snippet to the original code:
```
    c.close()
    await c.recv_state()
    assert c.State.Closed == await c.recv_state()
    assert len([ch for ch in s.children if ch.name=="server/blocks/client"])==0
```

The logs indicate that the channel is being destroyed as expected:
```
INFO : tll.channel.server/blocks/client: Destroy channel
INFO : tll.channel.server/blocks/client: State Closed -> Destroy
INFO : tll.channel.server/blocks/client: Recv message: type: State, msgid: Destroy
````

However, the final assertion fails, resulting in the following error:
```
>       assert len([ch for ch in s.children if ch.name=="server/blocks/client"])==0
E       assert 1 == 0
E         +1
E         -0
```
The issue stems from the use of unique_ptr for channels. When the unique_ptr is deleted, it triggers a mutating operation. The problem arises because callbacks capture the unique_ptr and these callbacks may still attempt to access the pointer after it has been nullified. For instance, in Rust this would not occur, as there would be no way to reset the pointer while it is still being shared by unprocessed callbacks.

**Comment by shramov** [comment]
Child channels are cleared when server processes client disconnect. This test is not correct - it shoud wait for Disconnect on server side.
Correct test added in 1e31e5d
